### ISSUE TITLE
[FEA] New brute-force API needs to support at least the metrics supported by FAISS' bfknn

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#1159]
It occured to me as I was reviewing https://github.com/rapidsai/cuml/pull/5140 that we are going to need to support (at the very least) all the same distance measures as the FAISS bfknn in order to keep the API matching what we had before. There are several algorithms on the cuML side which rely on these additional distance measures but we will need to at least support [these](https://github.com/rapidsai/raft/blob/branch-23.02/cpp/include/raft/spatial/knn/detail/common_faiss.h).

**Comment by benfred** [comment]
The big one that was missing was InnerProduct distance - which should be supported now with https://github.com/rapidsai/raft/pull/1226 . 

I've added tests for the other metrics you linked to [here](https://github.com/rapidsai/raft/pull/1202/commits/c734bace91a7b3d07caffef7aaeec65b2fc39c45) : it looks like BrayCurtis isn't supported by the pairwise distances API, and Jensen Shannon was producing incorrect results in the tests - but otherwise everything else is working.
