### ISSUE TITLE
[BUG] Segmentation fault in interruptible.hpp

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#1225]
cugraph has been encountering a segfault in `interruptible.hpp`. It seems to only appear when taking the Python path through their code, for some reason, but it's very consistent. The reproducer for this issue (assumes https://github.com/rapidsai/raft/pull/1224 has been reverted) is:

```python
import cugraph
import cudf
if __name__ == "__main__":

    edgelist = cudf.DataFrame( { "src": [0, 1, 2], "dst": [1, 2, 4], "wgt": [0.0, 0.1, 0.2], })
    G = cugraph.Graph()

    G.from_cudf_edgelist(edgelist, source="src", destination="dst", edge_attr="wgt", store_transposed=True)

    r = cugraph.pagerank(G)
```

And it's important to run this in a loop because it doesn't happen everytime:
```bash
while true; do python test_failure.py; if [$? -ne 0]; then break; fi; done
```

The following shows the error happening on line 214 [here](https://github.com/rapidsai/raft/blob/6a7e125bbb5ffdf195cd0fc50ec44aa28e6900bf/cpp/include/raft/core/interruptible.hpp#L214), which appears it might be related to an object being used in a callback after it's been cleaned up (something like `registry_.find(xxx)` after `registry_` has already been deallocated, maybe?)

![image](https://user-images.githubusercontent.com/1242464/216190835-9b4ed337-1b2a-4027-b0ac-bed319d02b7b.png)

cc @achirkin @tfeher 

I'm not sure why this doesn't seem to be happening in pylibraft, cuml, or cuopt but it's definitely consistently reproducible in cugraph. 

@ChuckHastings @alexbarghi-nv @rlratzel @seunghwak  @BradReesWork FYI

**Comment by achirkin** [comment]
Does cugraph run something in multiple processes there? The `registry_` is a static, global per-process variable, and the error seems to be happening at `__run_exit_handlers`, which happens at the program exit.
A wild guess: could it be related to the order of destruction between the `registry_` and the `mutex_`? What if the swap the two lines in here?https://github.com/rapidsai/raft/blob/6a7e125bbb5ffdf195cd0fc50ec44aa28e6900bf/cpp/include/raft/core/interruptible.hpp#L181-L184

**Comment by cjnolet** [comment]
@achirkin, I'm wondering if we could use somehting at the global level like a `std::atomic<bool>` flag that could be flipped to true when the deleter is called on the `registry_`? Can you think of any other way we might be able to check for this state so we can handle it gracefully?

cc @jrhemstad for thoughts as well- it looks like we have a race condition happening in the callback for `interruptible` where it's trying to use `registry_` after it's already been deleted. The order of deconstruction for static members seems to be inconsistent from behavior that @seunghwak has been seeing.

**Comment by seunghwak** [comment]
As I mentioned in the slack thread,

This is due to the arbitrary destruction order between `s` and `registry_`.
https://github.com/rapidsai/raft/blob/branch-23.02/cpp/include/raft/core/interruptible.hpp#L134
https://github.com/rapidsai/raft/blob/branch-23.02/cpp/include/raft/core/interruptible.hpp#L182

It seems like there is no guaranteed destruction order between a thread local static variable defined inside a member function and class member variables.

If `s` is destroyed after `registry_` is destroyed, `registry_` will be accessed after destruction.

I confirmed this is indeed happening by defining

```
class MyClass {
 public:
  MyClass() { std::cout << "MyClass() called" << std::endl; }
  ~MyClass() { std::cout << "~MyClass() called." << std::endl; }
};
```

and adding `static inline MyClass my_class_;` after `registry_` and `mutex_` (https://github.com/rapidsai/raft/blob/branch-23.02/cpp/include/raft/core/interruptible.hpp#L184).

Also added the printout statement in the custom deleter (https://github.com/rapidsai/raft/blob/branch-23.02/cpp/include/raft/core/interruptible.hpp#L213); this custom deleter will be called when `s` is destroyed.

In testing, the print statement from `~MyClass` appears before the print statement from the custom destructor, meaning the custom destructor can access `registry_` after destruction.

**Comment by achirkin** [comment]
Here's a rather ugly, but seemingly working, fix https://github.com/rapidsai/raft/pull/1229 - wrap the `registry_` in a shared pointer and use `weak_ptr.lock()` to avoid race conditions.
