### ISSUE TITLE
[BUG] `pylibraft.distance.pairwise_distance` gave inconsistent results

### ISSUE THREAD

**Issue by daxiongshu** [rapidsai/raft#1770]
**Describe the bug**
I run `pylibraft.distance.pairwise_distance` twice with the same inputs and got different outputs.

**Steps/Code to reproduce bug**
```
from pylibraft.distance import pairwise_distance
import cupy

x = cupy.asarray([[1,2,3]]).astype('float32')
y = cupy.asarray([[6,5,7]]).astype('float32')

output = pairwise_distance(x, y, metric="cosine")
print('pyraft cosine', output.ndarray_)

from cupyx.scipy.spatial.distance import cosine
print('cupy cosine', cosine(x, y))

output = pairwise_distance(x, y, metric="cosine")
print('pyraft cosine', output.ndarray_)
```

output:
```
pyraft cosine [[1.e-45]]
cupy cosine 0.057152748
pyraft cosine [[0.05715275]]
```
Note that the first pyraft output is wrong but the second pyraft output is correct.

**Expected behavior**
Consistent and correct outputs.

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of RAFT install: conda, 23.08

**Comment by cjnolet** [comment]
@daxiongshu, I'm posting my reply publicly for other future eyes that might have come to this issue for the same reasons.

We return a `device_ndarray` object from `pylibraft` functions but it's really just meant to be an internal facade for the device memory underneath so that we don't have to have an explicit dependency on cupy, cudf, or pytorch within `pylibraft`. That `ndarray_` attribute is really only meant to be used internally by pylibraft. The `device_ndarray` object itself also doesn't copy to host automatically, so `device_ndarray.copy_to_host()` would need to be invoked in order to get a numpy ndarray out of it.

But even more specifically, it's intended to just be an intermediate format that implements the cuda array interface for the purposes of holding into the memory allocation. Without copying the result to host, you can convert the `pylibraft.common.device_ndarray` to a cupy array by doing this (using your exmaple from above):

```
output = pairwise_distance(qemb, embs, metric="cosine")
output = cp.asarray(output)
```

The reason we designed it this way is so that you can use pytorch or cupy or cudf alongside pylibraft without having to worry about any potential conflicts in the dependencies between them.

**Comment by daxiongshu** [comment]
Thank you. It makes a lot of sense. I'm closing the issue.
