### ISSUE TITLE
[QST] Why is raft not something that is installed like a utils library we can all use?

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/raft#20]
Given that all of the projects in Rapids are trying to be on the same branch, following the same standards why is this not just a package that gets installed with rapids so we can use it without necessarily having to build it and can include it by assuming its just in "conda_prefix/include" for the c++ side and lib for the python stuff?

It seems strange that there will be a cuml.raft and a blazingsql.raft because thats how it adds raft to the packages right now.

**Comment by dantegd** [comment]
@felipeblazing I think you've been in contact with @cjnolet for this, but wanted to leave a response for reference of anyone else having this question. 

For now, RAFT has been designed as source-only/header only (both Python and C++). The source code is meant to be included in the consuming code bases without creating an additional conda package (this design was done mainly by the cuML and cuGraph teams to avoid version conflict headaches between the projects). So it is more similar to say cutlass/cub than it is to cuml/cudf. So there is no standalone binary that needs to be created for RAFT (at the moment I'm writing this), and it is meant to be consumed at build time (not runtime), either by git submodules, CMake git cloning and setup.py build as is described in https://github.com/rapidsai/raft/blob/branch-0.15/BUILD.md#usage-of-raft-by-downstream-projects. So the fact that there is a cuml.raft and a cugraph.raft (that might *not* point to the same commit in RAFT) is by design. 

Note that RAPIDS 0.15 is the first version where we will be adding and using significant functionality in RAFT, so the design/build/distribution process might be adjusted depending on how things work, community feedback, and whatnot.
