### ISSUE TITLE
[BUG] Handle.enable_rmm_pool method is missing

### ISSUE THREAD

**Issue by teju85** [rapidsai/raft#228]
**Describe the bug**
If one tries to call `model.enable_rmm_pool()` method ([implementation here](https://github.com/rapidsai/cuml/blob/branch-0.20/python/cuml/common/base.pyx#L213)) on any cuML algo object, I get the following error:
`AttributeError: 'cuml.raft.common.handle.Handle' object has no attribute 'enable_rmm_pool'`

**Steps/Code to reproduce bug**
Pick any cuML algo (for eg: ARIMA) and do the following:
```python
import cuml
model = cuml.tsa.ARIMA()
model.enable_rmm_pool()
```

**Expected behavior**
The call `enable_rmm_pool` used to initialize the rmm pool allocator for the subsequent usage in the algorithms.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)] [all]
 - Method of RAFT install: [conda, Docker, or from source] [all]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Additional context**
Even though this appears like a cuML bug, I'm filing this under raft as the handle wrapper is implemented here and cuML just delegates all calls to this wrapper.

**Comment by dantegd** [comment]
It seems to be that we should actually remove that method from the base of the estimators of cuML, since the way to enable RMM's pool is to use RMM itself with either `mm.reinitialize` or using the rmm memory resources directly, which gives more flexibility than just the pool. This method was back from when cuML was doing its own allocator plugin and device buffers, but that would go against #97

**Comment by teju85** [comment]
So, IIUC, until #97 is implemented, there will be no solution to using rmm pool allocator using raft handle, right @dantegd ?

**Comment by dantegd** [comment]
@teju85 no, RAFT's allocator already uses RMM under the hood https://github.com/rapidsai/raft/blob/fe5f40aad9159c60fbc53f80da689999c1e86203/cpp/include/raft/mr/device/allocator.hpp#L41 so by using RMM's API calls (say with `rmm.reinitialize` or `set_current_device_resource` for example) the pool allocator already works with cuML/RAFT code. The fact that that is what is happening indeed reinforces why using RMM directly is only logical since that is what we are essentially already doing just with extra steps.

**Comment by teju85** [comment]
Great. Thanks @dantegd for the confirmation. Then I'll file a PR to cuML to remove this offending method from cuml-handle.
