### ISSUE TITLE
[FEA] Use const for arguments to brute_force_knn

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#240]

**Comment by viclafargue** [comment]
After looking into it, I realized that the function do modify both the index partitions and the query with the help of the `MetricProcessor`. Marking arrays as constant would protect the input data against any damage. However, it would require to make copies of it (probably on GPU). This would probably halve the size of the largest dataset that could be processed. Would it be worth it? Also, you may have thoughts on how to avoid this problem?

**Comment by cjnolet** [comment]
@viclafargue, 

I think in general we want to get a point where we aren't having to modify the input data at all so that we can comfortably use the const on the public API without the need to cast it away. However, I think in the meantime we should be able introduce it into the public portion of the API and cast it away before modifying the inputs (with nice comments that state why we're doing this and that we plan for them to be removed in the future). What do you think?

**Comment by viclafargue** [comment]
Sure, I guess if it's temporary and well explained it should be fine. Maybe the next step would be to somehow make preprocessing part of the nearest neighbors CUDA kernel. That way, the preprocessed data would be in registers or shared memory instead of being stored as a copy in global memory. This option might be interesting at least for the query that is only used once.

**Comment by cjnolet** [comment]
This will be fixed in the move to cuvs when we establish a more consistent API experience (cc @benfred)
