### ISSUE TITLE
[FEA] Conversion between 1-dim mdspan and span.

### ISSUE THREAD

**Issue by trivialfis** [rapidsai/raft#479]
There should be a trivial conversion from span to 1-dim mdspan.  Also, we can consider adding a conversion for the other way around if the 1-dim mdspan is contiguous.

**Comment by mhoemmen** [comment]
@trivialfis wrote:
> There should be a trivial conversion from span to 1-dim mdspan.

That's a bit hard now, given that mdspan has already been approved for C++23.  Would you like us to write a follow-on paper?  The paper is unlikely to make C++23 unless we hurry (NB comment period, currently our only option for C++23, will close at some point) but possible for C++26.  We'll also have to convince the P0009 coauthors.

For now, users could do this conversion inline when calling a function that takes a rank-1 mdspan.

https://godbolt.org/z/oKdv1rzoP

```c++
namespace stdex = std::experimental;
void function_taking_mdspan(stdex::mdspan<float, stdex::dextents<std::size_t, 1>>) {}
int main() {
  constexpr std::size_t number_of_elements = 11;
  std::vector<float> v(number_of_elements);
  std::span s{v.data(), v.size()};
  function_taking_mdspan(stdex::mdspan{s.data(), s.size()});
  return 0;
}
```

> Also, we can consider adding a conversion for the other way around if the 1-dim mdspan is contiguous.

P0009 dropped requiring a "backing `span`" at some point in its history.  (The explicit conversion to `span` was removed before Revision 11.)  The idea is that `data_handle_type` doesn't have to be a pointer (`ElementType*`) or refer to any contiguous span of memory.

We could consider _conditional_ conversion to `span` for 1-D, strided, exhausive (recall that "exhaustive" does not necessarily mean linear order), `default_accessor` mdspan.  However, if you know your mdspan that well, you could just write an explicit specialization, as in the code below.  It's hard to imagine how conditional conversion to `span` could make generic code easier to write. 

In the example below, I have a function `compute` that takes a rank-1 mdspan.  It has a "fast" implementation that takes `span`.  The code that converts mdspan to span might not even _compile_ (because `data_handle_type` need not be a pointer), so I have to protect it behind `if constexpr`.  It's much more trouble to figure out if an mdspan `m` is convertible to `span`, than it is to type `span{m.data_handle(), m.required_span_size()}`.

```c++
// Could the mdspan be convertible to span, contingent on run-time information?
template<class Mdspan>
constexpr bool never_convertible_to_span_v = true;

// extents<IndexType, Extent> has rank 1.
template<class ElementType, class IndexType, size_t Extent, class Layout>
constexpr bool never_convertible_to_span_v<
  mdspan<ElementType, extents<IndexType, Extent>, Layout, default_accessor<ElementType>>> = false;

// Can the mdspan actually be converted to span?
template<class ElementType, class IndexType, size_t Extent, class Layout>
constexpr bool convertible_to_span_v(
  mdspan<ElementType, extents<IndexType, Extent>, Layout, default_accessor<ElementType>> m)
{
  return m.is_exhaustive() && m.is_strided();
}

float fast_specialized_compute(std::span<const float> s);

template<class Layout, class Accessor>
float compute(mdspan<const float, dextents<size_t, 1>, Layout, Accessor> m)
{
  if constexpr (never_convertible_to_span_v<decltype(m)>) { // generic code
    auto s = init_function<float>();
    for(size_t k = 0; k < m.extent(0); ++k) {
      s += some_function(m[k]);
    }
    return another_function(s);
  }
  else {
    if (convertible_to_span_v(m)) { // a run-time question in general
      // Explicit conversion to span won't even compile
      // unless `data_handle` returns an actual raw pointer type.
      return fast_specialized_compute(std::span{m.data_handle(), m.required_span_size()});
    }
  }
}
```

I would propose closing this issue.  My view is that implicit conversion between mdspan and span is not as useful as one might think, given how specific an mdspan has to be in order for this conversion to compile and be correct.  If we do want to keep this issue open, then we'll need to write a WG21 proposal.

Thanks!

**Comment by trivialfis** [comment]
Thank you for the detailed analysis! It makes sense to keep them as it is.
