### ISSUE TITLE
[QST] `libraft-headers` list in conda recipes' `requirements/run`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/raft#637]
It appears that `libraft-headers` appears in `requirements/run` of a few packages. Though if `libraft-headers` is just headers, wouldn't expect them to be needed at runtime. Are `libraft-headers` used for some runtime compilation, do they contain some libraries, or is there something else particular about its usage that results in it being needed at runtime?

**Comment by cjnolet** [comment]
> Are libraft-headers used for some runtime compilation, do they contain some libraries, or is there something else particular about its usage that results in it being needed at runtime?

We've been moving stuff around and consolidating conventions to make it easier for users to know the expectations of certain headers, but the answer to this is that yes, RAFT is a compile-time dependency for the projects which depend on it, but its headers may also be a runtime dependency, for example, in the case where RAFT APIs are exposed on that project's public APIs. For example, there are two ways in RAFT to tell if a header is safe to expose on a public API (that is, it doesn't require `nvcc` to compile, nor additional dependencies outside of the minimal dependencies listed in the documentation:

1. The contents of `include/raft/core`
2. Any headers with the suffix `*_types.hpp` 

In terms of RAPIDS projects, I think it's safer that the projects include RAFT as both the `host` and `run` dependency because if a developer inadvertently exposes a raft type through their public API, they're more likely to get confused when users complain of the raft headers not being available when they go to build against it.
