### ISSUE TITLE
[BUG] Fix clang-tidy errors

### ISSUE THREAD

**Issue by teju85** [rapidsai/raft#84]
**Describe the bug**
In the past we had to disable parsing of `.cu` files in `run-clang-tidy.py` due to difficulties in trying to get them working properly. So, we never tidied our cuda source files!

**Steps/Code to reproduce bug**
Today, if we path this script with the following change:
```
diff --git a/cpp/scripts/run-clang-tidy.py b/cpp/scripts/run-clang-tidy.py
index 23260d2..fdb0abc 100644
--- a/cpp/scripts/run-clang-tidy.py
+++ b/cpp/scripts/run-clang-tidy.py
@@ -36,7 +36,7 @@ def parse_args():
                            help="Path to cmake-generated compilation database")
     argparser.add_argument("-exe", type=str, default="clang-tidy",
                            help="Path to clang-tidy exe")
-    argparser.add_argument("-ignore", type=str, default="[.]cu$",
+    argparser.add_argument("-ignore", type=str, default=None,
                            help="Regex used to ignore files from checking")
     argparser.add_argument("-select", type=str, default=None,
                            help="Regex used to select files for checking")
@@ -123,6 +123,10 @@ def get_tidy_args(cmd, exe):
         # replace nvcc's "-gencode ..." with clang's "--cuda-gpu-arch ..."
         archs = get_gpu_archs(command)
         command.extend(archs)
+        # clang-tooling 8.0.1 doesn't support linking with greater sm_70 archs
+        # so, we need to disable libdevice linkage, until we are in a position
+        # to upgrade clang-tooling
+        command.extend(["-nocudalib", "--no-cuda-version-check"])
         while True:
             loc = remove_item_plus_one(command, "-gencode")
             if loc < 0:
```
and then run the script, we get a ton of errors which we never caught before (and thus never fixed). Full list of all the errors in here: [run.log](https://github.com/rapidsai/raft/files/5414273/run.log)

**Expected behavior**
tidy check should pass on all source files, irrespective of device or host code.

**Comment by MatthiasKohl** [comment]
I'd like to come back to this issue and fix clang compilation in raft.
There are several things that I can see after attempting to compile all raft test codes with clang:
1. A few minor things due to the CUDA/C `__host__` / `__device__` overloads which `nvcc` and `clang++` treat differently (mainly functions such as `min` / `fmin` etc.)
2. The fact that raft has a dependency on cub which is too old to be compiled by clang: we should update this to >= 1.14
3. A few issues with `static const` vs `static constexpr` : should be easy to handle since raft is C++ >= 11
4. There seem to be some issues with template parameters in KNN which I still have to figure out
